apiVersion: v1
kind: Service
metadata:
  name: {{ include "samplewh.name" . }}
  labels:
{{ include "samplewh.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "samplewh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
